# SPDX-FileCopyrightText: 2021 Centrum Wiskune en Informatica
#
# SPDX-License-Identifier: CC0-1.0

repos:
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    additional_dependencies:
      - types-requests
- repo: https://github.com/fsfe/reuse-tool
  rev: v0.13.0
  hooks:
  - id: reuse
- repo: local
  hooks:
  - id: pytest-cov
    name: pytest
    stages: [commit]
    language: system
    entry: pdm run pytest --vcr-record=none --cov --cov-fail-under=100
    pass_filenames: false
    types: [python]
